name: Test Node

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  test-node:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repo
        uses: actions/checkout@v4

      - name: Set up Node
        uses: actions/setup-node@v3
        with:
          node-version: 20
          cache: npm

      - name: Install dependencies
        run: npm ci

      - name: Run lint
        run: npm run lint

      - name: Run server
        env:
          PORT: 5555
        run: |
          npm run start > /tmp/stdout.log 2> /tmp/stderr.log &
          sleep 2

      - name: Ping server
        run: curl --retry-connrefused --retry 4 http://localhost:5555/

      - name: Send something
        run: |
          curl -X POST http://localhost:5555/api/error -d '{"message": "teststring"}' -H 'Content-Type: application/json'

      - name: Inspect db
        run: |
          # If 'grep' fails, jq couldn't find what it expected
          cat db.json | jq ".errors[0].body.message" | grep teststring

      - name: Inspect stdout
        run: |
          cat /tmp/stdout.log
          cat /tmp/stdout.log | grep "POSTING to /api/error"

      - if: ${{ failure() }}
        name: Debug server outputs on errors
        run: |
          echo "____STDOUT____"
          cat /tmp/stdout.log
          echo "____STDERR____"
          cat /tmp/stderr.log
